version: '3.9'

services:
  fast-api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8008:8008
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8008

    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=geniass
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lox